container-engine/guides/example-image.mdx

Title case this header

---

container-engine/gettingstartedwithsaladcloud.mdx

Made the following changes:
1. Added a callout specifically for IPv6 development and considerations, linking to our already-existing docs.
2. Added a more detailed description to the "What is the right Salad product for my workload?" question.
3. Add a callout for another hidden cost that Salad does not charge versus other providers, "stale pod charges" (storage)

Updating the SCE Getting Started Guide

---

products/sce/imds/Container-status-endpoint.mdx
products/sce/imds/imds-reallocate.mdx
products/sce/imds/obtaining-an-imds-jwt.mdx

Polishes the new IMDS how-tos:

IMDS how-to polish

---

.github/CONTRIBUTING.md
scripts/add-all-endpoints

There's some automation for adding endpoints to the docs, and this PR documents how to use that automation.

update guide for contributing endpoints

---

mint.json

- removed duplicate menu item "billing and pricing"

remove billing and pricing duplicate

---

api-specs/s4.yml
mint.json
reference/s4/delete-a-file.mdx
reference/s4/download-a-file.mdx
reference/s4/list-all-files-that-belong-to-the-organization.mdx
reference/s4/sign-a-file-and-return-a-signed-url.mdx
reference/s4/upload-a-file.mdx

- Adds the s4 api. Cool side effect, this provides a gui for uploading files.

add s4 to api spec

---

products/recipes/dreamshaper8-comfyui.mdx
products/recipes/flux1-schnell-fp8-comfyui.mdx
products/recipes/sdxl-with-refiner-comfyui.mdx

- Adds links to the recipe product pages that go to the benchmarks on the blog site.

Recipe performance links

---

.github/CONTRIBUTING.md

- Adds details to the contributing guide

add details to contributing page

---

api-specs/s4.yml
api-specs/transcribe.json
guides/transcription/salad-transcription-api/captions.mdx
guides/transcription/salad-transcription-api/pabblyintegration.mdx
guides/transcription/salad-transcription-api/transcription-quick-start.mdx
guides/transcription/salad-transcription-api/transcriptionfaq.mdx
guides/transcription/salad-transcription-api/translation.mdx
mint.json
products/documentation.mdx
products/quickstart.mdx
products/recipes/dreamshaper8-comfyui.mdx
products/recipes/overview.mdx
products/recipes/sdxl-with-refiner-comfyui.mdx
products/s4/salad-simple-storage-service.mdx
products/sce/container-groups/health-probes/health-probes.mdx
products/sce/faqs.mdx
products/sce/introduction.mdx
products/sgs/introduction.mdx
products/transcription/captions.mdx
products/transcription/insights-intelligence.mdx
products/transcription/speech-to-text.mdx
products/transcription/transcription-overview.mdx
products/transcription/translation.mdx
tutorials/how-to-deploy-a-node-app-on-salad/index.mdx

Thanks @seanwmiller for catching the brand inconsistencies there. Must have gotten too aggressive on a previous find&replace.

Brand consistency

---

guides/transcription/salad-transcription-api/captions.mdx
guides/transcription/salad-transcription-api/llm-features.mdx
guides/transcription/salad-transcription-api/speech-to-text.mdx
mint.json
products/transcription/insights-intelligence.mdx
products/transcription/transcription-overview.mdx

Added  Turnaround Times to overview page: 
Added llm feature pages to product and guides: 
Updated name to Salad Transcription API in a few places

Transcription docs update

---

guides/transcription/salad-transcription-api/transcription-quick-start.mdx
products/transcription/transcription-overview.mdx

Add info about free trial to transcription product overview and quick start pages  

---

mint.json
products/transcription/billing.mdx
products/transcription/transcription-overview.mdx

Add a page around transcription billing

---

mint.json
products/sce/container-groups/billing-and-pricing/prepaid-billing-faqs.mdx

Adding prepaid billing FAQs during the transition period under the

Add Prepaid Billing FAQs

---

products/sce/container-groups/billing-and-pricing/prepaid-billing-faqs.mdx

There was an influx of AppSumo users coming into support after the announcement of the shift to prepaid billing. Adding a question to the FAQ to cover this.

Adding AppSumo to Prepaid Billing FAQs

---

dictionaries/salad-cloud.txt
guides/transcription/salad-transcription-api/transcribe-youtube.mdx
mint.json

Page describing how pull audios from youtube videos and send them for transcription :

How to transcribe youtube videos with transcription api

---

guides/transcription/salad-transcription-api/migrate-to-salad-transcription-api/migrate-from-azure-batch.mdx
mint.json

Moves transcription API migration to guides section, and adds additional items to comparison table

moves transcription migration to guides

---

api-specs/salad-cloud.yaml

This updates the SaladCloud API reference to the latest version. Notably, this deprecates the Workload Errors and introduces the much-improved System Logs.

Update SaladCloud API reference

---

mint.json
reference/saladcloud-api/container_groups/get-container-group-system-logs.mdx
reference/saladcloud-api/organizations/get-webhook-secret-key.mdx
reference/saladcloud-api/organizations/update-webhook-secret-key.mdx

This adds a few new SaladCloud API methods to the left hand navigation.

Add links to new SaladCloud API methods

---

LICENSE-CODE
README.md
api-specs/salad-cloud.yaml

This adds SDK code samples to the SaladCloud API reference.

Add SDK code samples to SaladCloud API reference

---

dictionaries/salad-cloud.txt
guides/transcription/salad-transcription-api/migrate-to-salad-transcription-api/migrate-from-assembly-transcription.mdx
mint.json

adds Assembly migration guide

---

docs.json
guides/transcription/salad-transcription-api/identify-hate-speech.mdx
guides/transcription/salad-transcription-api/transcribe-a-local-file.mdx

adds hate speech detection cookbook, and fixes some spelling in some earlier cookbooks to be consistent

adds hate speech detection cookbook

---

guides/transcription/salad-transcription-api/llm-features.mdx
guides/transcription/salad-transcription-api/transcription-quick-start.mdx
guides/transcription/salad-transcription-api/translation.mdx
products/documentation.mdx
products/transcription/billing.mdx
products/transcription/captions.mdx
products/transcription/insights-intelligence.mdx
products/transcription/speech-to-text.mdx
products/transcription/transcription-overview.mdx
products/transcription/translation.mdx

First update to docs side to include Transcription Lite

First batch of docs updates to include lite

---

dictionaries/salad-cloud.txt
docs.json
guides/transcription/salad-transcription-api/transcribe-vimeo.mdx

Adds guide to transcribe batch Vimeo videos

Adds guide to transcribe batch Vimeo videos

---

products/sgs/sgs-api.mdx

Thanks for opening a pull request! Here are some tips:
- Review the contributing guidelines and code of conduct.
- Include a description of your changes.
- Ensure the GitHub Actions complete successfully.
- Screenshots of the changes are helpful.

Sgs api docs fixes

---

.gitignore
docs.json
tutorials/long-running-jobs.mdx
tutorials/performance-monitoring.mdx

- Adds a tutorial for implementing ongoing performance checks
- Updates the long running task tutorial to point to more and newer resources

Performance Monitoring

---

dictionaries/salad-cloud.txt
docs.json
products/transcription/accuracy-benchmarks.mdx
products/transcription/transcription-overview.mdx

Added a new page under products: 
Updated overview page:

Adding accuracy benchmarks

---

products/transcription/billing.mdx

adding price tier table to billing page

add price tiers to transcriptipn billing page

---

docs.json
guides/transcription/salad-transcription-api/transcribe-facebook.mdx

Adds Facebook video transcription cookbook

Facebook video transcription cookbook

---

vimeo.js

This adds the Vimeo-Google Analytics integration script. This will help us identify engagement with our new video content.

Add Vimeo analytics

---

products/sce/container-groups/quotas.mdx

Updates the SCE quotas page to account for the changes to quotas

Quotas update

---

docs.json
transcription/explanation/overview.mdx
transcription/how-to-guides/sdk/python-sdk-examples.mdx
transcription/how-to-guides/sdk/python-sdk-quick-start.mdx
transcription/how-to-guides/sdk/python-sdk.mdx
transcription/tutorials/transcription-quick-start.mdx

adding
- sdk section under transcription
- python sdk overview page 
- python sdk quick start
- python sdk examples page
updated
- transcription overview page 
- quickstart page

Python Transcription SDK docs

---

container-engine/explanation/infrastructure-platform/container-registries.mdx

Added documentation for container image caching. This section will be linked from the portal.

Add caching information for container images

---

container-engine/reference/recipes/vllm.mdx
docs.json

Docs for vLLm recipe run on consumer gpu's

Vllm recipe
