SaladTechnologies/salad-cloud-docs

container-engine/gettingstartedwithsaladcloud.mdx
In reference to @seniorquico's comment on #55: https://github.com/SaladTechnologies/salad-cloud-docs/pull/55#discussion_r1771621600
Adjusting the reference of stale pod to be consistent with Salad's terminology of containers.
=> Updating "stale pod" reference

helpscout.js
This adds the Help Scout beacon to the website to power a SaladCloud Support contact form.
=> Add Help Scout beacon to show contact form

README.md, mint.json, support.mdx, support/abuse.mdx, support/contact.mdx, support/sales.mdx, support/status.mdx
This adds additional details on our support plan response times, incorporates the support links in the sidebar navigation, and reorders the README... sharing the "getting started" bits before the _boring_ license details. 😅
=> Add support plan details

mint.json, support/abuse.mdx, support/sales.mdx, support/status.mdx
This reverts a portion of #66- the new, custom sidebar navigation for the support pages. It all looked fine and worked as expected locally... but after deploying to the production site, we get two "Product" navigation tabs. 🤔
=> Remove support navigation

.github/CONTRIBUTING.md
- updates contribution guidelines to use the `add-recipe` script when adding recipes.
=> update recipe contribution guide

mint.json
We've got some broken links out in the wild, not unexpected from the massive re-org. This fixes the ones we know about so far.
From google search console:
=> Redirects round 1

.github/scripts/validate-all-workflows.sh, .github/workflows/openapi-validate.yml
Since there are many (and growing) API specs now, I changed the validator check to check any json or yaml file in the api specs repo. this way we don't have to maintain a growing list in the action.
=> validate all schemas in the specs folder

products/sce/container-groups/container-logs.mdx, products/sce/container-groups/faqs.mdx, products/sce/introduction.mdx
- Specify that container logging is done through `stderr` and `stdout`
- Point to terminal as alternative to ssh
- Explain building for amd64
- Explain why workloads have less than 100% vram in wsl2
- Explain that container instance storage is ephemeral
=> hopefully clarify some peculiarities

dictionaries/salad-cloud.txt, products/sgs/node-removals.mdx
There were several outdated items in the Node Removal guidelines. Fixed those, and hopefully made the section more clear - trying to make the node removal API more usable while discouraging overuse.
=> Updated node removals docs for clarity and correctness, overuse warning

products/recipes/dreamshaper8-comfyui.mdx, products/recipes/flux1-schnell-fp8-comfyui.mdx, products/recipes/ollama-llama3.1.mdx, products/recipes/sd3.5-large.mdx, products/recipes/sd3.5-medium.mdx, products/recipes/sdxl-with-refiner-comfyui.mdx, products/recipes/yolov8.mdx
- Adds a section to the bottom of every recipe page that links to the recipes repo directory that it is built from.
- Adds a link to the api reference for the sd3.5 recipes
=> add link to recipes repo for all recipe product pages

.github/scripts/validate-all-workflows.sh, .github/workflows/stale.yml, .vscode/settings.json, package-lock.json, package.json
This applies some minor updates to the repo's GitHub Actions and project configuration. Notably, it switches from the abandoned `@apidevtools/swagger-cli` to the `mintlify` CLI to validate OpenAPI Specification documents.
=> Update GitHub Actions

products/sce/container-groups/billing-and-pricing/billing.mdx, products/sce/container-groups/billing-and-pricing/prepaid-billing-faqs.mdx
We've now transitioned to prepaid billing, so transition directions are no longer relevant. Also removed "& Pricing" form the title - I wouldn't consider this page to have pricing info.
=> Remove references to prepaid billing transition

dictionaries/salad-cloud.txt, guides/transcription/salad-transcription-api/migrate-to-salad-transcription-api/migrate-from-azure-batch.mdx, guides/transcription/salad-transcription-api/migrate-to-salad-transcription-api/migrate-from-gcp-transcription.mdx, mint.json
Adds a guide to migrate from GCP transcription to the Salad Transcription API.
Also updates the feature comparison table in the existing Azure one to be more clear.
=> Migration guide for GCP Transcription

guides/image-generation/deploy-video-gen-on-salad-with-comfy.mdx, products/sce/job-queues/creating-a-job-queue.mdx, products/sce/job-queues/job-queues.mdx
- We have removed job queues from the portal, and they are now an api only feature. This updates a couple places that referenced using the portal to instead direct to the create job queue endpoint in reference.
=> Hiding queues from portal

products/documentation.mdx
Trying out front-page callouts for migration guides
=> Migration guides callout on front page

products/sce/autoscaling/enable-autoscaling.mdx
We don't have autoscaling options in the Portal, so removing them from docs
=> Removes Portal instructions for setting up autoscaling

products/documentation.mdx
Puts a card to the amazon transcribe migration guide on the front page
=> add a card to front page for migration guide

products/sce/faqs.mdx
Adds some info to the SCE FAQ page about current limitations regarding the RTX 5090.
https://salad-rtx5090-warnings.mintlify.app/products/sce/faqs#rtx-5090-gpus-on-saladcloud%3F
=> Rtx5090 warnings

products/documentation.mdx, products/sce/faqs.mdx
- Adds migration card for deepgram to the front page with the rest of the transcription migration guides.
- fix "last updated"
=> add card for deepgram to front page

guides/image-generation/basic-how-to-deploy-flux-on-salad-comfy.mdx, guides/image-generation/basic-how-to-deploy-stable-diffusion-on-salad-comfy.mdx, guides/image-generation/deploy-video-gen-on-salad-with-comfy.mdx, products/recipes/dreamshaper8-comfyui.mdx, products/recipes/flux1-dev-fp8-comfyui.mdx, products/recipes/flux1-schnell-fp8-comfyui.mdx, products/recipes/sd3.5-large.mdx, products/recipes/sd3.5-medium.mdx, products/recipes/sdxl-with-refiner-comfyui.mdx
There are some outdated references in the image gen documentation. Also added text to all the image gen recipes that specify we do not host the web ui.
=> Update image gen guides

docs.json, products/sce/faqs.mdx, tutorials/pytorch-rtx5090.mdx
- Adds a tutorial on how to make a pytorch container that works with cuda 12.8, i.e. rtx 5090, 5080
- Verified this works by building a comfy image from it and running it on a 5090 successfully
https://salad-torch-nightly-50-series.mintlify.app/tutorials/pytorch-rtx5090
=> Tutorial for Cuda 12.8 and pytorch

api-specs/transcribe.json, guides/transcription/salad-transcription-api/speech-to-text.mdx, guides/transcription/salad-transcription-api/transcription-quick-start.mdx
A few pages updated to add language codes supported. (Fireflies feedback):
API Reference: 
Quick start page. Added a line about accuracy benchmaks:
Speech to text page:
=> update language codes for transcription api

docs.json
Simple fix to docs.json for typo
=> Fix name of docs file in docs.json

.github/scripts/validate_docs_json.py, .github/workflows/docs-json-validate.yml, .gitignore
Turns out a valid mintlify staging deployment does not mean it will deploy in production. Having invalid page entries in docs.json can cause it to not deploy *only in production*. It still appears to work correctly locally, and in staging.
=> github action to validate docs.json
